services:
  client:
    image: client-img
    container_name: client
    build:
      context: ./Client
      dockerfile: dev.dockerfile
    ports:
      - "80:4200"
    volumes:
      - type: bind
        source: ./Client/src/
        target: /client/src/

  server:
    image: server-img
    container_name: server
    build:
      context: ./Server
      dockerfile: dev.dockerfile
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
    volumes:
      - type: bind
        source: ./Server/src/
        target: /server/src/


  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      PG_DATA: /pg-data
    volumes:
      - db-volume:/pg-data
      - type: bind
        source: ./db-init-scripts
        target: /docker-entrypoint-initdb.d
      - type: bind
        source: ./db-images
        target: /db-images

volumes:
  db-volume:
